[tool.black]
line-length = 120
target-version = ['py38']
exclude = '/migrations/'
experimental-string-processing = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
force_sort_within_sections = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'DJANGO', 'DJANGOTHIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
known_django = ['django']
known_djangothirdparty = ['environ', 'huey.contrib', 'constance', 'dirtyfields', 'django_redis', 'django_select2']
skip = ['migrations']

[tool.pytest.ini_options]
addopts = '-s --cov=. --cov-report=term-missing'
python_files = 'tests.py'
cache_dir = '/tmp/.pytest_cache'
